#include <Util.h>

#include <string>
#include <WiFi.h>

std::string generate_hostname(std::string prefix){
    
    String get_base_mac = WiFi.macAddress();
    const char* base_mac = get_base_mac.c_str();
    
    std::string hostname = prefix + std::string("_") 
                            + base_mac[9] + base_mac[10]
                            + base_mac[12] + base_mac[13]
                            + base_mac[15] + base_mac[16];

    return hostname;
}

// // https://raw.githubusercontent.com/nayarsystems/posix_tz_db/refs/heads/master/zones.csv
// std::string get_timezone_code(std::string timezone)
// {
//         if(timezone == "Africa/Abidjan"){ return "GMT0"; }
//         if(timezone == "Africa/Accra"){ return "GMT0"; }
//         if(timezone == "Africa/Addis_Ababa"){ return "EAT-3"; }
//         if(timezone == "Africa/Algiers"){ return "CET-1"; }
//         if(timezone == "Africa/Asmara"){ return "EAT-3"; }
//         if(timezone == "Africa/Bamako"){ return "GMT0"; }
//         if(timezone == "Africa/Bangui"){ return "WAT-1"; }
//         if(timezone == "Africa/Banjul"){ return "GMT0"; }
//         if(timezone == "Africa/Bissau"){ return "GMT0"; }
//         if(timezone == "Africa/Blantyre"){ return "CAT-2"; }
//         if(timezone == "Africa/Brazzaville"){ return "WAT-1"; }
//         if(timezone == "Africa/Bujumbura"){ return "CAT-2"; }
//         if(timezone == "Africa/Cairo"){ return "EET-2EEST,M4.5.5/0,M10.5.4/24"; }
//         if(timezone == "Africa/Casablanca"){ return "<+01>-1"; }
//         if(timezone == "Africa/Ceuta"){ return "CET-1CEST,M3.5.0,M10.5.0/3"; }
//         if(timezone == "Africa/Conakry"){ return "GMT0"; }
//         if(timezone == "Africa/Dakar"){ return "GMT0"; }
//         if(timezone == "Africa/Dar_es_Salaam"){ return "EAT-3"; }
//         if(timezone == "Africa/Djibouti"){ return "EAT-3"; }
//         if(timezone == "Africa/Douala"){ return "WAT-1"; }
//         if(timezone == "Africa/El_Aaiun"){ return "<+01>-1"; }
//         if(timezone == "Africa/Freetown"){ return "GMT0"; }
//         if(timezone == "Africa/Gaborone"){ return "CAT-2"; }
//         if(timezone == "Africa/Harare"){ return "CAT-2"; }
//         if(timezone == "Africa/Johannesburg"){ return "SAST-2"; }
//         if(timezone == "Africa/Juba"){ return "CAT-2"; }
//         if(timezone == "Africa/Kampala"){ return "EAT-3"; }
//         if(timezone == "Africa/Khartoum"){ return "CAT-2"; }
//         if(timezone == "Africa/Kigali"){ return "CAT-2"; }
//         if(timezone == "Africa/Kinshasa"){ return "WAT-1"; }
//         if(timezone == "Africa/Lagos"){ return "WAT-1"; }
//         if(timezone == "Africa/Libreville"){ return "WAT-1"; }
//         if(timezone == "Africa/Lome"){ return "GMT0"; }
//         if(timezone == "Africa/Luanda"){ return "WAT-1"; }
//         if(timezone == "Africa/Lubumbashi"){ return "CAT-2"; }
//         if(timezone == "Africa/Lusaka"){ return "CAT-2"; }
//         if(timezone == "Africa/Malabo"){ return "WAT-1"; }
//         if(timezone == "Africa/Maputo"){ return "CAT-2"; }
//         if(timezone == "Africa/Maseru"){ return "SAST-2"; }
//         if(timezone == "Africa/Mbabane"){ return "SAST-2"; }
//         if(timezone == "Africa/Mogadishu"){ return "EAT-3"; }
//         if(timezone == "Africa/Monrovia"){ return "GMT0"; }
//         if(timezone == "Africa/Nairobi"){ return "EAT-3"; }
//         if(timezone == "Africa/Ndjamena"){ return "WAT-1"; }
//         if(timezone == "Africa/Niamey"){ return "WAT-1"; }
//         if(timezone == "Africa/Nouakchott"){ return "GMT0"; }
//         if(timezone == "Africa/Ouagadougou"){ return "GMT0"; }
//         if(timezone == "Africa/Porto-Novo"){ return "WAT-1"; }
//         if(timezone == "Africa/Sao_Tome"){ return "GMT0"; }
//         if(timezone == "Africa/Tripoli"){ return "EET-2"; }
//         if(timezone == "Africa/Tunis"){ return "CET-1"; }
//         if(timezone == "Africa/Windhoek"){ return "CAT-2"; }
//         if(timezone == "America/Adak"){ return "HST10HDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Anchorage"){ return "AKST9AKDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Anguilla"){ return "AST4"; }
//         if(timezone == "America/Antigua"){ return "AST4"; }
//         if(timezone == "America/Araguaina"){ return "<-03>3"; }
//         if(timezone == "America/Argentina/Buenos_Aires"){ return "<-03>3"; }
//         if(timezone == "America/Argentina/Catamarca"){ return "<-03>3"; }
//         if(timezone == "America/Argentina/Cordoba"){ return "<-03>3"; }
//         if(timezone == "America/Argentina/Jujuy"){ return "<-03>3"; }
//         if(timezone == "America/Argentina/La_Rioja"){ return "<-03>3"; }
//         if(timezone == "America/Argentina/Mendoza"){ return "<-03>3"; }
//         if(timezone == "America/Argentina/Rio_Gallegos"){ return "<-03>3"; }
//         if(timezone == "America/Argentina/Salta"){ return "<-03>3"; }
//         if(timezone == "America/Argentina/San_Juan"){ return "<-03>3"; }
//         if(timezone == "America/Argentina/San_Luis"){ return "<-03>3"; }
//         if(timezone == "America/Argentina/Tucuman"){ return "<-03>3"; }
//         if(timezone == "America/Argentina/Ushuaia"){ return "<-03>3"; }
//         if(timezone == "America/Aruba"){ return "AST4"; }
//         if(timezone == "America/Asuncion"){ return "<-04>4<-03>,M10.1.0/0,M3.4.0/0"; }
//         if(timezone == "America/Atikokan"){ return "EST5"; }
//         if(timezone == "America/Bahia"){ return "<-03>3"; }
//         if(timezone == "America/Bahia_Banderas"){ return "CST6"; }
//         if(timezone == "America/Barbados"){ return "AST4"; }
//         if(timezone == "America/Belem"){ return "<-03>3"; }
//         if(timezone == "America/Belize"){ return "CST6"; }
//         if(timezone == "America/Blanc-Sablon"){ return "AST4"; }
//         if(timezone == "America/Boa_Vista"){ return "<-04>4"; }
//         if(timezone == "America/Bogota"){ return "<-05>5"; }
//         if(timezone == "America/Boise"){ return "MST7MDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Cambridge_Bay"){ return "MST7MDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Campo_Grande"){ return "<-04>4"; }
//         if(timezone == "America/Cancun"){ return "EST5"; }
//         if(timezone == "America/Caracas"){ return "<-04>4"; }
//         if(timezone == "America/Cayenne"){ return "<-03>3"; }
//         if(timezone == "America/Cayman"){ return "EST5"; }
//         if(timezone == "America/Chicago"){ return "CST6CDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Chihuahua"){ return "CST6"; }
//         if(timezone == "America/Costa_Rica"){ return "CST6"; }
//         if(timezone == "America/Creston"){ return "MST7"; }
//         if(timezone == "America/Cuiaba"){ return "<-04>4"; }
//         if(timezone == "America/Curacao"){ return "AST4"; }
//         if(timezone == "America/Danmarkshavn"){ return "GMT0"; }
//         if(timezone == "America/Dawson"){ return "MST7"; }
//         if(timezone == "America/Dawson_Creek"){ return "MST7"; }
//         if(timezone == "America/Denver"){ return "MST7MDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Detroit"){ return "EST5EDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Dominica"){ return "AST4"; }
//         if(timezone == "America/Edmonton"){ return "MST7MDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Eirunepe"){ return "<-05>5"; }
//         if(timezone == "America/El_Salvador"){ return "CST6"; }
//         if(timezone == "America/Fortaleza"){ return "<-03>3"; }
//         if(timezone == "America/Fort_Nelson"){ return "MST7"; }
//         if(timezone == "America/Glace_Bay"){ return "AST4ADT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Godthab"){ return "<-02>2<-01>,M3.5.0/-1,M10.5.0/0"; }
//         if(timezone == "America/Goose_Bay"){ return "AST4ADT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Grand_Turk"){ return "EST5EDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Grenada"){ return "AST4"; }
//         if(timezone == "America/Guadeloupe"){ return "AST4"; }
//         if(timezone == "America/Guatemala"){ return "CST6"; }
//         if(timezone == "America/Guayaquil"){ return "<-05>5"; }
//         if(timezone == "America/Guyana"){ return "<-04>4"; }
//         if(timezone == "America/Halifax"){ return "AST4ADT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Havana"){ return "CST5CDT,M3.2.0/0,M11.1.0/1"; }
//         if(timezone == "America/Hermosillo"){ return "MST7"; }
//         if(timezone == "America/Indiana/Indianapolis"){ return "EST5EDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Indiana/Knox"){ return "CST6CDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Indiana/Marengo"){ return "EST5EDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Indiana/Petersburg"){ return "EST5EDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Indiana/Tell_City"){ return "CST6CDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Indiana/Vevay"){ return "EST5EDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Indiana/Vincennes"){ return "EST5EDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Indiana/Winamac"){ return "EST5EDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Inuvik"){ return "MST7MDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Iqaluit"){ return "EST5EDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Jamaica"){ return "EST5"; }
//         if(timezone == "America/Juneau"){ return "AKST9AKDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Kentucky/Louisville"){ return "EST5EDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Kentucky/Monticello"){ return "EST5EDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Kralendijk"){ return "AST4"; }
//         if(timezone == "America/La_Paz"){ return "<-04>4"; }
//         if(timezone == "America/Lima"){ return "<-05>5"; }
//         if(timezone == "America/Los_Angeles"){ return "PST8PDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Lower_Princes"){ return "AST4"; }
//         if(timezone == "America/Maceio"){ return "<-03>3"; }
//         if(timezone == "America/Managua"){ return "CST6"; }
//         if(timezone == "America/Manaus"){ return "<-04>4"; }
//         if(timezone == "America/Marigot"){ return "AST4"; }
//         if(timezone == "America/Martinique"){ return "AST4"; }
//         if(timezone == "America/Matamoros"){ return "CST6CDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Mazatlan"){ return "MST7"; }
//         if(timezone == "America/Menominee"){ return "CST6CDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Merida"){ return "CST6"; }
//         if(timezone == "America/Metlakatla"){ return "AKST9AKDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Mexico_City"){ return "CST6"; }
//         if(timezone == "America/Miquelon"){ return "<-03>3<-02>,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Moncton"){ return "AST4ADT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Monterrey"){ return "CST6"; }
//         if(timezone == "America/Montevideo"){ return "<-03>3"; }
//         if(timezone == "America/Montreal"){ return "EST5EDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Montserrat"){ return "AST4"; }
//         if(timezone == "America/Nassau"){ return "EST5EDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/New_York"){ return "EST5EDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Nipigon"){ return "EST5EDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Nome"){ return "AKST9AKDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Noronha"){ return "<-02>2"; }
//         if(timezone == "America/North_Dakota/Beulah"){ return "CST6CDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/North_Dakota/Center"){ return "CST6CDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/North_Dakota/New_Salem"){ return "CST6CDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Nuuk"){ return "<-02>2<-01>,M3.5.0/-1,M10.5.0/0"; }
//         if(timezone == "America/Ojinaga"){ return "CST6CDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Panama"){ return "EST5"; }
//         if(timezone == "America/Pangnirtung"){ return "EST5EDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Paramaribo"){ return "<-03>3"; }
//         if(timezone == "America/Phoenix"){ return "MST7"; }
//         if(timezone == "America/Port-au-Prince"){ return "EST5EDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Port_of_Spain"){ return "AST4"; }
//         if(timezone == "America/Porto_Velho"){ return "<-04>4"; }
//         if(timezone == "America/Puerto_Rico"){ return "AST4"; }
//         if(timezone == "America/Punta_Arenas"){ return "<-03>3"; }
//         if(timezone == "America/Rainy_River"){ return "CST6CDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Rankin_Inlet"){ return "CST6CDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Recife"){ return "<-03>3"; }
//         if(timezone == "America/Regina"){ return "CST6"; }
//         if(timezone == "America/Resolute"){ return "CST6CDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Rio_Branco"){ return "<-05>5"; }
//         if(timezone == "America/Santarem"){ return "<-03>3"; }
//         if(timezone == "America/Santiago"){ return "<-04>4<-03>,M9.1.6/24,M4.1.6/24"; }
//         if(timezone == "America/Santo_Domingo"){ return "AST4"; }
//         if(timezone == "America/Sao_Paulo"){ return "<-03>3"; }
//         if(timezone == "America/Scoresbysund"){ return "<-02>2<-01>,M3.5.0/-1,M10.5.0/0"; }
//         if(timezone == "America/Sitka"){ return "AKST9AKDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/St_Barthelemy"){ return "AST4"; }
//         if(timezone == "America/St_Johns"){ return "NST3:30NDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/St_Kitts"){ return "AST4"; }
//         if(timezone == "America/St_Lucia"){ return "AST4"; }
//         if(timezone == "America/St_Thomas"){ return "AST4"; }
//         if(timezone == "America/St_Vincent"){ return "AST4"; }
//         if(timezone == "America/Swift_Current"){ return "CST6"; }
//         if(timezone == "America/Tegucigalpa"){ return "CST6"; }
//         if(timezone == "America/Thule"){ return "AST4ADT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Thunder_Bay"){ return "EST5EDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Tijuana"){ return "PST8PDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Toronto"){ return "EST5EDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Tortola"){ return "AST4"; }
//         if(timezone == "America/Vancouver"){ return "PST8PDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Whitehorse"){ return "MST7"; }
//         if(timezone == "America/Winnipeg"){ return "CST6CDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Yakutat"){ return "AKST9AKDT,M3.2.0,M11.1.0"; }
//         if(timezone == "America/Yellowknife"){ return "MST7MDT,M3.2.0,M11.1.0"; }
//         if(timezone == "Antarctica/if(timezone ==y"){ return "<+08>-8"; }
//         if(timezone == "Antarctica/Davis"){ return "<+07>-7"; }
//         if(timezone == "Antarctica/DumontDUrville"){ return "<+10>-10"; }
//         if(timezone == "Antarctica/Macquarie"){ return "AEST-10AEDT,M10.1.0,M4.1.0/3"; }
//         if(timezone == "Antarctica/Mawson"){ return "<+05>-5"; }
//         if(timezone == "Antarctica/McMurdo"){ return "NZST-12NZDT,M9.5.0,M4.1.0/3"; }
//         if(timezone == "Antarctica/Palmer"){ return "<-03>3"; }
//         if(timezone == "Antarctica/Rothera"){ return "<-03>3"; }
//         if(timezone == "Antarctica/Syowa"){ return "<+03>-3"; }
//         if(timezone == "Antarctica/Troll"){ return "<+00>0<+02>-2,M3.5.0/1,M10.5.0/3"; }
//         if(timezone == "Antarctica/Vostok"){ return "<+05>-5"; }
//         if(timezone == "Arctic/Longyearbyen"){ return "CET-1CEST,M3.5.0,M10.5.0/3"; }
//         if(timezone == "Asia/Aden"){ return "<+03>-3"; }
//         if(timezone == "Asia/Almaty"){ return "<+05>-5"; }
//         if(timezone == "Asia/Amman"){ return "<+03>-3"; }
//         if(timezone == "Asia/Anadyr"){ return "<+12>-12"; }
//         if(timezone == "Asia/Aqtau"){ return "<+05>-5"; }
//         if(timezone == "Asia/Aqtobe"){ return "<+05>-5"; }
//         if(timezone == "Asia/Ashgabat"){ return "<+05>-5"; }
//         if(timezone == "Asia/Atyrau"){ return "<+05>-5"; }
//         if(timezone == "Asia/Baghdad"){ return "<+03>-3"; }
//         if(timezone == "Asia/Bahrain"){ return "<+03>-3"; }
//         if(timezone == "Asia/Baku"){ return "<+04>-4"; }
//         if(timezone == "Asia/Bangkok"){ return "<+07>-7"; }
//         if(timezone == "Asia/Barnaul"){ return "<+07>-7"; }
//         if(timezone == "Asia/Beirut"){ return "EET-2EEST,M3.5.0/0,M10.5.0/0"; }
//         if(timezone == "Asia/Bishkek"){ return "<+06>-6"; }
//         if(timezone == "Asia/Brunei"){ return "<+08>-8"; }
//         if(timezone == "Asia/Chita"){ return "<+09>-9"; }
//         if(timezone == "Asia/Choibalsan"){ return "<+08>-8"; }
//         if(timezone == "Asia/Colombo"){ return "<+0530>-5:30"; }
//         if(timezone == "Asia/Damascus"){ return "<+03>-3"; }
//         if(timezone == "Asia/Dhaka"){ return "<+06>-6"; }
//         if(timezone == "Asia/Dili"){ return "<+09>-9"; }
//         if(timezone == "Asia/Dubai"){ return "<+04>-4"; }
//         if(timezone == "Asia/Dushanbe"){ return "<+05>-5"; }
//         if(timezone == "Asia/Famagusta"){ return "EET-2EEST,M3.5.0/3,M10.5.0/4"; }
//         if(timezone == "Asia/Gaza"){ return "EET-2EEST,M3.4.4/50,M10.4.4/50"; }
//         if(timezone == "Asia/Hebron"){ return "EET-2EEST,M3.4.4/50,M10.4.4/50"; }
//         if(timezone == "Asia/Ho_Chi_Minh"){ return "<+07>-7"; }
//         if(timezone == "Asia/Hong_Kong"){ return "HKT-8"; }
//         if(timezone == "Asia/Hovd"){ return "<+07>-7"; }
//         if(timezone == "Asia/Irkutsk"){ return "<+08>-8"; }
//         if(timezone == "Asia/Jakarta"){ return "WIB-7"; }
//         if(timezone == "Asia/Jayapura"){ return "WIT-9"; }
//         if(timezone == "Asia/Jerusalem"){ return "IST-2IDT,M3.4.4/26,M10.5.0"; }
//         if(timezone == "Asia/Kabul"){ return "<+0430>-4:30"; }
//         if(timezone == "Asia/Kamchatka"){ return "<+12>-12"; }
//         if(timezone == "Asia/Karachi"){ return "PKT-5"; }
//         if(timezone == "Asia/Kathmandu"){ return "<+0545>-5:45"; }
//         if(timezone == "Asia/Khandyga"){ return "<+09>-9"; }
//         if(timezone == "Asia/Kolkata"){ return "IST-5:30"; }
//         if(timezone == "Asia/Krasnoyarsk"){ return "<+07>-7"; }
//         if(timezone == "Asia/Kuala_Lumpur"){ return "<+08>-8"; }
//         if(timezone == "Asia/Kuching"){ return "<+08>-8"; }
//         if(timezone == "Asia/Kuwait"){ return "<+03>-3"; }
//         if(timezone == "Asia/Macau"){ return "CST-8"; }
//         if(timezone == "Asia/Magadan"){ return "<+11>-11"; }
//         if(timezone == "Asia/Makassar"){ return "WITA-8"; }
//         if(timezone == "Asia/Manila"){ return "PST-8"; }
//         if(timezone == "Asia/Muscat"){ return "<+04>-4"; }
//         if(timezone == "Asia/Nicosia"){ return "EET-2EEST,M3.5.0/3,M10.5.0/4"; }
//         if(timezone == "Asia/Novokuznetsk"){ return "<+07>-7"; }
//         if(timezone == "Asia/Novosibirsk"){ return "<+07>-7"; }
//         if(timezone == "Asia/Omsk"){ return "<+06>-6"; }
//         if(timezone == "Asia/Oral"){ return "<+05>-5"; }
//         if(timezone == "Asia/Phnom_Penh"){ return "<+07>-7"; }
//         if(timezone == "Asia/Pontianak"){ return "WIB-7"; }
//         if(timezone == "Asia/Pyongyang"){ return "KST-9"; }
//         if(timezone == "Asia/Qatar"){ return "<+03>-3"; }
//         if(timezone == "Asia/Qyzylorda"){ return "<+05>-5"; }
//         if(timezone == "Asia/Riyadh"){ return "<+03>-3"; }
//         if(timezone == "Asia/Sakhalin"){ return "<+11>-11"; }
//         if(timezone == "Asia/Samarkand"){ return "<+05>-5"; }
//         if(timezone == "Asia/Seoul"){ return "KST-9"; }
//         if(timezone == "Asia/Shanghai"){ return "CST-8"; }
//         if(timezone == "Asia/Singapore"){ return "<+08>-8"; }
//         if(timezone == "Asia/Srednekolymsk"){ return "<+11>-11"; }
//         if(timezone == "Asia/Taipei"){ return "CST-8"; }
//         if(timezone == "Asia/Tashkent"){ return "<+05>-5"; }
//         if(timezone == "Asia/Tbilisi"){ return "<+04>-4"; }
//         if(timezone == "Asia/Tehran"){ return "<+0330>-3:30"; }
//         if(timezone == "Asia/Thimphu"){ return "<+06>-6"; }
//         if(timezone == "Asia/Tokyo"){ return "JST-9"; }
//         if(timezone == "Asia/Tomsk"){ return "<+07>-7"; }
//         if(timezone == "Asia/Ulaanbaatar"){ return "<+08>-8"; }
//         if(timezone == "Asia/Urumqi"){ return "<+06>-6"; }
//         if(timezone == "Asia/Ust-Nera"){ return "<+10>-10"; }
//         if(timezone == "Asia/Vientiane"){ return "<+07>-7"; }
//         if(timezone == "Asia/Vladivostok"){ return "<+10>-10"; }
//         if(timezone == "Asia/Yakutsk"){ return "<+09>-9"; }
//         if(timezone == "Asia/Yangon"){ return "<+0630>-6:30"; }
//         if(timezone == "Asia/Yekaterinburg"){ return "<+05>-5"; }
//         if(timezone == "Asia/Yerevan"){ return "<+04>-4"; }
//         if(timezone == "Atlantic/Azores"){ return "<-01>1<+00>,M3.5.0/0,M10.5.0/1"; }
//         if(timezone == "Atlantic/Bermuda"){ return "AST4ADT,M3.2.0,M11.1.0"; }
//         if(timezone == "Atlantic/Canary"){ return "WET0WEST,M3.5.0/1,M10.5.0"; }
//         if(timezone == "Atlantic/Cape_Verde"){ return "<-01>1"; }
//         if(timezone == "Atlantic/Faroe"){ return "WET0WEST,M3.5.0/1,M10.5.0"; }
//         if(timezone == "Atlantic/Madeira"){ return "WET0WEST,M3.5.0/1,M10.5.0"; }
//         if(timezone == "Atlantic/Reykjavik"){ return "GMT0"; }
//         if(timezone == "Atlantic/South_Georgia"){ return "<-02>2"; }
//         if(timezone == "Atlantic/Stanley"){ return "<-03>3"; }
//         if(timezone == "Atlantic/St_Helena"){ return "GMT0"; }
//         if(timezone == "Australia/Adelaide"){ return "ACST-9:30ACDT,M10.1.0,M4.1.0/3"; }
//         if(timezone == "Australia/Brisbane"){ return "AEST-10"; }
//         if(timezone == "Australia/Broken_Hill"){ return "ACST-9:30ACDT,M10.1.0,M4.1.0/3"; }
//         if(timezone == "Australia/Currie"){ return "AEST-10AEDT,M10.1.0,M4.1.0/3"; }
//         if(timezone == "Australia/Darwin"){ return "ACST-9:30"; }
//         if(timezone == "Australia/Eucla"){ return "<+0845>-8:45"; }
//         if(timezone == "Australia/Hobart"){ return "AEST-10AEDT,M10.1.0,M4.1.0/3"; }
//         if(timezone == "Australia/Lindeman"){ return "AEST-10"; }
//         if(timezone == "Australia/Lord_Howe"){ return "<+1030>-10:30<+11>-11,M10.1.0,M4.1.0"; }
//         if(timezone == "Australia/Melbourne"){ return "AEST-10AEDT,M10.1.0,M4.1.0/3"; }
//         if(timezone == "Australia/Perth"){ return "AWST-8"; }
//         if(timezone == "Australia/Sydney"){ return "AEST-10AEDT,M10.1.0,M4.1.0/3"; }
//         if(timezone == "Europe/Amsterdam"){ return "CET-1CEST,M3.5.0,M10.5.0/3"; }
//         if(timezone == "Europe/Andorra"){ return "CET-1CEST,M3.5.0,M10.5.0/3"; }
//         if(timezone == "Europe/Astrakhan"){ return "<+04>-4"; }
//         if(timezone == "Europe/Athens"){ return "EET-2EEST,M3.5.0/3,M10.5.0/4"; }
//         if(timezone == "Europe/Belgrade"){ return "CET-1CEST,M3.5.0,M10.5.0/3"; }
//         if(timezone == "Europe/Berlin"){ return "CET-1CEST,M3.5.0,M10.5.0/3"; }
//         if(timezone == "Europe/Bratislava"){ return "CET-1CEST,M3.5.0,M10.5.0/3"; }
//         if(timezone == "Europe/Brussels"){ return "CET-1CEST,M3.5.0,M10.5.0/3"; }
//         if(timezone == "Europe/Bucharest"){ return "EET-2EEST,M3.5.0/3,M10.5.0/4"; }
//         if(timezone == "Europe/Budapest"){ return "CET-1CEST,M3.5.0,M10.5.0/3"; }
//         if(timezone == "Europe/Busingen"){ return "CET-1CEST,M3.5.0,M10.5.0/3"; }
//         if(timezone == "Europe/Chisinau"){ return "EET-2EEST,M3.5.0,M10.5.0/3"; }
//         if(timezone == "Europe/Copenhagen"){ return "CET-1CEST,M3.5.0,M10.5.0/3"; }
//         if(timezone == "Europe/Dublin"){ return "IST-1GMT0,M10.5.0,M3.5.0/1"; }
//         if(timezone == "Europe/Gibraltar"){ return "CET-1CEST,M3.5.0,M10.5.0/3"; }
//         if(timezone == "Europe/Guernsey"){ return "GMT0BST,M3.5.0/1,M10.5.0"; }
//         if(timezone == "Europe/Helsinki"){ return "EET-2EEST,M3.5.0/3,M10.5.0/4"; }
//         if(timezone == "Europe/Isle_of_Man"){ return "GMT0BST,M3.5.0/1,M10.5.0"; }
//         if(timezone == "Europe/Istanbul"){ return "<+03>-3"; }
//         if(timezone == "Europe/Jersey"){ return "GMT0BST,M3.5.0/1,M10.5.0"; }
//         if(timezone == "Europe/Kaliningrad"){ return "EET-2"; }
//         if(timezone == "Europe/Kiev"){ return "EET-2EEST,M3.5.0/3,M10.5.0/4"; }
//         if(timezone == "Europe/Kirov"){ return "MSK-3"; }
//         if(timezone == "Europe/Lisbon"){ return "WET0WEST,M3.5.0/1,M10.5.0"; }
//         if(timezone == "Europe/Ljubljana"){ return "CET-1CEST,M3.5.0,M10.5.0/3"; }
//         if(timezone == "Europe/London"){ return "GMT0BST,M3.5.0/1,M10.5.0"; }
//         if(timezone == "Europe/Luxembourg"){ return "CET-1CEST,M3.5.0,M10.5.0/3"; }
//         if(timezone == "Europe/Madrid"){ return "CET-1CEST,M3.5.0,M10.5.0/3"; }
//         if(timezone == "Europe/Malta"){ return "CET-1CEST,M3.5.0,M10.5.0/3"; }
//         if(timezone == "Europe/Mariehamn"){ return "EET-2EEST,M3.5.0/3,M10.5.0/4"; }
//         if(timezone == "Europe/Minsk"){ return "<+03>-3"; }
//         if(timezone == "Europe/Monaco"){ return "CET-1CEST,M3.5.0,M10.5.0/3"; }
//         if(timezone == "Europe/Moscow"){ return "MSK-3"; }
//         if(timezone == "Europe/Oslo"){ return "CET-1CEST,M3.5.0,M10.5.0/3"; }
//         if(timezone == "Europe/Paris"){ return "CET-1CEST,M3.5.0,M10.5.0/3"; }
//         if(timezone == "Europe/Podgorica"){ return "CET-1CEST,M3.5.0,M10.5.0/3"; }
//         if(timezone == "Europe/Prague"){ return "CET-1CEST,M3.5.0,M10.5.0/3"; }
//         if(timezone == "Europe/Riga"){ return "EET-2EEST,M3.5.0/3,M10.5.0/4"; }
//         if(timezone == "Europe/Rome"){ return "CET-1CEST,M3.5.0,M10.5.0/3"; }
//         if(timezone == "Europe/Samara"){ return "<+04>-4"; }
//         if(timezone == "Europe/San_Marino"){ return "CET-1CEST,M3.5.0,M10.5.0/3"; }
//         if(timezone == "Europe/Sarajevo"){ return "CET-1CEST,M3.5.0,M10.5.0/3"; }
//         if(timezone == "Europe/Saratov"){ return "<+04>-4"; }
//         if(timezone == "Europe/Simferopol"){ return "MSK-3"; }
//         if(timezone == "Europe/Skopje"){ return "CET-1CEST,M3.5.0,M10.5.0/3"; }
//         if(timezone == "Europe/Sofia"){ return "EET-2EEST,M3.5.0/3,M10.5.0/4"; }
//         if(timezone == "Europe/Stockholm"){ return "CET-1CEST,M3.5.0,M10.5.0/3"; }
//         if(timezone == "Europe/Tallinn"){ return "EET-2EEST,M3.5.0/3,M10.5.0/4"; }
//         if(timezone == "Europe/Tirane"){ return "CET-1CEST,M3.5.0,M10.5.0/3"; }
//         if(timezone == "Europe/Ulyanovsk"){ return "<+04>-4"; }
//         if(timezone == "Europe/Uzhgorod"){ return "EET-2EEST,M3.5.0/3,M10.5.0/4"; }
//         if(timezone == "Europe/Vaduz"){ return "CET-1CEST,M3.5.0,M10.5.0/3"; }
//         if(timezone == "Europe/Vatican"){ return "CET-1CEST,M3.5.0,M10.5.0/3"; }
//         if(timezone == "Europe/Vienna"){ return "CET-1CEST,M3.5.0,M10.5.0/3"; }
//         if(timezone == "Europe/Vilnius"){ return "EET-2EEST,M3.5.0/3,M10.5.0/4"; }
//         if(timezone == "Europe/Volgograd"){ return "MSK-3"; }
//         if(timezone == "Europe/Warsaw"){ return "CET-1CEST,M3.5.0,M10.5.0/3"; }
//         if(timezone == "Europe/Zagreb"){ return "CET-1CEST,M3.5.0,M10.5.0/3"; }
//         if(timezone == "Europe/Zaporozhye"){ return "EET-2EEST,M3.5.0/3,M10.5.0/4"; }
//         if(timezone == "Europe/Zurich"){ return "CET-1CEST,M3.5.0,M10.5.0/3"; }
//         if(timezone == "Indian/Antananarivo"){ return "EAT-3"; }
//         if(timezone == "Indian/Chagos"){ return "<+06>-6"; }
//         if(timezone == "Indian/Christmas"){ return "<+07>-7"; }
//         if(timezone == "Indian/Cocos"){ return "<+0630>-6:30"; }
//         if(timezone == "Indian/Comoro"){ return "EAT-3"; }
//         if(timezone == "Indian/Kerguelen"){ return "<+05>-5"; }
//         if(timezone == "Indian/Mahe"){ return "<+04>-4"; }
//         if(timezone == "Indian/Maldives"){ return "<+05>-5"; }
//         if(timezone == "Indian/Mauritius"){ return "<+04>-4"; }
//         if(timezone == "Indian/Mayotte"){ return "EAT-3"; }
//         if(timezone == "Indian/Reunion"){ return "<+04>-4"; }
//         if(timezone == "Pacific/Apia"){ return "<+13>-13"; }
//         if(timezone == "Pacific/Auckland"){ return "NZST-12NZDT,M9.5.0,M4.1.0/3"; }
//         if(timezone == "Pacific/Bougainville"){ return "<+11>-11"; }
//         if(timezone == "Pacific/Chatham"){ return "<+1245>-12:45<+1345>,M9.5.0/2:45,M4.1.0/3:45"; }
//         if(timezone == "Pacific/Chuuk"){ return "<+10>-10"; }
//         if(timezone == "Pacific/Easter"){ return "<-06>6<-05>,M9.1.6/22,M4.1.6/22"; }
//         if(timezone == "Pacific/Efate"){ return "<+11>-11"; }
//         if(timezone == "Pacific/Enderbury"){ return "<+13>-13"; }
//         if(timezone == "Pacific/Fakaofo"){ return "<+13>-13"; }
//         if(timezone == "Pacific/Fiji"){ return "<+12>-12"; }
//         if(timezone == "Pacific/Funafuti"){ return "<+12>-12"; }
//         if(timezone == "Pacific/Galapagos"){ return "<-06>6"; }
//         if(timezone == "Pacific/Gambier"){ return "<-09>9"; }
//         if(timezone == "Pacific/Guadalcanal"){ return "<+11>-11"; }
//         if(timezone == "Pacific/Guam"){ return "ChST-10"; }
//         if(timezone == "Pacific/Honolulu"){ return "HST10"; }
//         if(timezone == "Pacific/Kiritimati"){ return "<+14>-14"; }
//         if(timezone == "Pacific/Kosrae"){ return "<+11>-11"; }
//         if(timezone == "Pacific/Kwajalein"){ return "<+12>-12"; }
//         if(timezone == "Pacific/Majuro"){ return "<+12>-12"; }
//         if(timezone == "Pacific/Marquesas"){ return "<-0930>9:30"; }
//         if(timezone == "Pacific/Midway"){ return "SST11"; }
//         if(timezone == "Pacific/Nauru"){ return "<+12>-12"; }
//         if(timezone == "Pacific/Niue"){ return "<-11>11"; }
//         if(timezone == "Pacific/Norfolk"){ return "<+11>-11<+12>,M10.1.0,M4.1.0/3"; }
//         if(timezone == "Pacific/Noumea"){ return "<+11>-11"; }
//         if(timezone == "Pacific/Pago_Pago"){ return "SST11"; }
//         if(timezone == "Pacific/Palau"){ return "<+09>-9"; }
//         if(timezone == "Pacific/Pitcairn"){ return "<-08>8"; }
//         if(timezone == "Pacific/Pohnpei"){ return "<+11>-11"; }
//         if(timezone == "Pacific/Port_Moresby"){ return "<+10>-10"; }
//         if(timezone == "Pacific/Rarotonga"){ return "<-10>10"; }
//         if(timezone == "Pacific/Saipan"){ return "ChST-10"; }
//         if(timezone == "Pacific/Tahiti"){ return "<-10>10"; }
//         if(timezone == "Pacific/Tarawa"){ return "<+12>-12"; }
//         if(timezone == "Pacific/Tongatapu"){ return "<+13>-13"; }
//         if(timezone == "Pacific/Wake"){ return "<+12>-12"; }
//         if(timezone == "Pacific/Wallis"){ return "<+12>-12"; }
//         if(timezone == "Etc/GMT"){ return "GMT0"; }
//         if(timezone == "Etc/GMT-0"){ return "GMT0"; }
//         if(timezone == "Etc/GMT-1"){ return "<+01>-1"; }
//         if(timezone == "Etc/GMT-2"){ return "<+02>-2"; }
//         if(timezone == "Etc/GMT-3"){ return "<+03>-3"; }
//         if(timezone == "Etc/GMT-4"){ return "<+04>-4"; }
//         if(timezone == "Etc/GMT-5"){ return "<+05>-5"; }
//         if(timezone == "Etc/GMT-6"){ return "<+06>-6"; }
//         if(timezone == "Etc/GMT-7"){ return "<+07>-7"; }
//         if(timezone == "Etc/GMT-8"){ return "<+08>-8"; }
//         if(timezone == "Etc/GMT-9"){ return "<+09>-9"; }
//         if(timezone == "Etc/GMT-10"){ return "<+10>-10"; }
//         if(timezone == "Etc/GMT-11"){ return "<+11>-11"; }
//         if(timezone == "Etc/GMT-12"){ return "<+12>-12"; }
//         if(timezone == "Etc/GMT-13"){ return "<+13>-13"; }
//         if(timezone == "Etc/GMT-14"){ return "<+14>-14"; }
//         if(timezone == "Etc/GMT0"){ return "GMT0"; }
//         if(timezone == "Etc/GMT+0"){ return "GMT0"; }
//         if(timezone == "Etc/GMT+1"){ return "<-01>1"; }
//         if(timezone == "Etc/GMT+2"){ return "<-02>2"; }
//         if(timezone == "Etc/GMT+3"){ return "<-03>3"; }
//         if(timezone == "Etc/GMT+4"){ return "<-04>4"; }
//         if(timezone == "Etc/GMT+5"){ return "<-05>5"; }
//         if(timezone == "Etc/GMT+6"){ return "<-06>6"; }
//         if(timezone == "Etc/GMT+7"){ return "<-07>7"; }
//         if(timezone == "Etc/GMT+8"){ return "<-08>8"; }
//         if(timezone == "Etc/GMT+9"){ return "<-09>9"; }
//         if(timezone == "Etc/GMT+10"){ return "<-10>10"; }
//         if(timezone == "Etc/GMT+11"){ return "<-11>11"; }
//         if(timezone == "Etc/GMT+12"){ return "<-12>12"; }
//         if(timezone == "Etc/UCT"){ return "UTC0"; }
//         if(timezone == "Etc/UTC"){ return "UTC0"; }
//         if(timezone == "Etc/Greenwich"){ return "GMT0"; }
//         if(timezone == "Etc/Universal"){ return "UTC0"; }
//         if(timezone == "Etc/Zulu"){ return "UTC0"; }

//         //Default as fallback
//         return "UTC0";
// }