"""Builds the web frontend into lib/Website/WebApp.h.

Inlines the stylesheet and scripts that web/index.html references into one page, gzips it and
writes it as a C byte array with an ETag. PlatformIO runs this before every build (extra_scripts in
platformio.ini). It can also be run by hand: python tools/build_web.py
"""
import gzip
import hashlib
import os
import re

MAX_GZIP_BYTES = 50 * 1024

try:
    Import("env")  # noqa: F821 - provided by PlatformIO/SCons
    PROJECT_DIR = env.subst("$PROJECT_DIR")  # noqa: F821
    RUNNING_IN_PLATFORMIO = True
except NameError:
    PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    RUNNING_IN_PLATFORMIO = False


def read(folder, name):
    with open(os.path.join(folder, name), encoding="utf-8") as f:
        return f.read()


def inline_page(web_dir):
    """Returns index.html with its stylesheet and scripts inlined, in the order they appear."""
    html = read(web_dir, "index.html")
    html = re.sub(r'<link rel="stylesheet" href="([^"]+)">',
                  lambda m: "<style>\n" + read(web_dir, m.group(1)) + "\n</style>", html)
    html = re.sub(r'<script src="([^"]+)"></script>',
                  lambda m: "<script>\n" + read(web_dir, m.group(1)) + "\n</script>", html)
    return html


def header(data, etag):
    """Returns the C header holding the gzipped page."""
    rows = []
    for start in range(0, len(data), 20):
        rows.append("    " + ", ".join("0x%02x" % b for b in data[start:start + 20]) + ",")
    return (
        "// Generated by tools/build_web.py from web/, do not edit\n"
        "#pragma once\n"
        "#include <Arduino.h>\n"
        "\n"
        'const char WEB_APP_ETAG[] = "\\"%s\\"";\n'
        "const size_t WEB_APP_GZ_LEN = %d;\n"
        "const uint8_t WEB_APP_GZ[] PROGMEM = {\n"
        "%s\n"
        "};\n" % (etag, len(data), "\n".join(rows))
    )


def build():
    web_dir = os.path.join(PROJECT_DIR, "web")
    if not os.path.isdir(web_dir):
        raise SystemExit("build_web: web/ folder not found")

    page = inline_page(web_dir).encode("utf-8")
    data = gzip.compress(page, compresslevel=9, mtime=0)
    if len(data) > MAX_GZIP_BYTES:
        raise SystemExit("build_web: gzipped page is %d bytes, the limit is %d" % (len(data), MAX_GZIP_BYTES))

    content = header(data, hashlib.sha1(data).hexdigest()[:12])
    out = os.path.join(PROJECT_DIR, "lib", "Website", "WebApp.h")

    # Only write when something changed, so an unchanged frontend doesn't trigger a rebuild
    current = None
    if os.path.exists(out):
        with open(out, encoding="utf-8") as f:
            current = f.read()
    if current != content:
        with open(out, "w", encoding="utf-8", newline="\n") as f:
            f.write(content)

    print("build_web: %d bytes html, %d bytes gzipped" % (len(page), len(data)))


if RUNNING_IN_PLATFORMIO or __name__ == "__main__":
    build()
