openapi: '3.1.1'
info:
  title: Free-Grilly
  version: '25.3.27'
  description: The local Free-Grilly api

externalDocs:
  url: https://github.com/epiecs/free-grilly
  description: Git repository

servers:
  - url: http://{free-grilly-ip}/api
    variables:
      free-grilly-ip:
        default: 192.168.200.10
        description: Your Free-Grilly ip address

tags:
  - name: grill
    description: Grill overview with current status and temperatures
  - name: probes
    description: Detailed probe data and settings
  - name: settings
    description: Settings management
  - name: utility
    description: Utility api calls

components:
  responses:
    '400':
      description: Malformatted body
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                default: "malformatted body"
                enum:
                  - malformatted body
                  - empty body
  schemas:
    Grill:
      type: object
      properties:
        name:
          type: string
          example: Free-Grilly
          description: The chosen grill name
        unique_id:
          type: string
          format: uuid
          example: 12abc3de-4567-89f0-a123-456b789012c3
          description: The unique id in UUIDv4 format
        firmware_version:
          type: string
          example: 25.03.01
          description: The current firmware version in CalVer
        battery_percentage:
          type: integer
          example: 95
          description: The current - estimated - battery %
        battery_charging:
          type: boolean
          example: true
          description: If the battery is charging
        wifi_connected:
          type: boolean
          example: true
          description: If the grill is connected to a wifi network
        wifi_ssid:
          type: string
          example: my-home-wifi
          description: The name of the wifi network that the grill is connected to
        wifi_signal:
          type: integer
          example: -61
          description: The wifi signal expressed in dbm. The closer to 0 the better.
        wifi_ip:
          type: string
          example: 192.168.0.10
          description: The wifi ip when connected to your network
        temperature_unit:
          type: string
          description: The temperature_unit that is used
          example: celcius
          default: celcius    
          enum:
            - celcius
            - fahrenheit
        probes:
          type: array
          minItems: 8
          maxItems: 8
          items:
            type: object
            properties:
              probe_id:
                type: integer
                description: The number of the probe
              temperature:
                type: 
                  - "number"
                  - "null"
                format: float
                description: The temperature in Celcius/Fahrenheit
              minimum_temperature:
                type: 
                  - "number"
                  - "null"
                format: float
                description: The minimum temperature in Celcius/Fahrenheit according to the settings. Used for temperature ranges.
                examples:
                  - 30.00
                  - 25.5
              target_temperature:
                type: 
                  - "number"
                  - "null"
                format: float
                description: The target temperature in Celcius/Fahrenheit
                examples:
                  - 30.00
                  - 25.5
              connected:
                type: boolean
                description: Is the probe connected
            example:
              - probe_id: 1
                temperature: 23.71832
                minimum_temperature: null
                target_temperature: 23.71832
                connected: true
              - probe_id: 2
                temperature: null
                minimum_temperature: null
                target_temperature: null
                connected: false
              - probe_id: 3
                temperature: 110.12578
                minimum_temperature: 90.00001
                target_temperature: 120.00001
                connected: true
              - probe_id: 4
                temperature: 250.12578
                minimum_temperature: null
                target_temperature: 280.12578
                connected: true
              - probe_id: 5
                temperature: null
                minimum_temperature: null
                target_temperature: null
                connected: false
              - probe_id: 6
                temperature: null
                minimum_temperature: null
                target_temperature: null
                connected: false
              - probe_id: 7
                temperature: null
                minimum_temperature: null
                target_temperature: null
                connected: false
              - probe_id: 8
                temperature: null
                minimum_temperature: null
                target_temperature: null
                connected: false
    
    Probe:
      type: object
      properties:
        probe_id:
          type: integer
          description: The number of the probe
          examples:
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
        name:
          type: string
          example: Probe 1
          description: The probe name
        temperature:
          type: 
            - "number"
            - "null"
          format: float
          readOnly: true
          description: The temperature in Celcius/Fahrenheit according to the settings.
          examples:
            - 25.101
            - 27.101
            - 150.33
        minimum_temperature:
          type: 
            - "number"
            - "null"
          format: float
          description: The minimum temperature in Celcius/Fahrenheit according to the settings. Used for temperature ranges.
          default: 0
          examples:
            - 25.50
            - 120
        target_temperature:
          type: 
            - "number"
            - "null"
          format: float
          description: The target temperature in Celcius/Fahrenheit according to the settings.
          default: 0
          examples:
            - 25.50
            - 120
        connected:
          type: boolean
          description: Is the probe connected
          readOnly: true
        probe_type:
          type: string
          description: >
            The probe type connected to the grilleye. There are several built-in probe types. If 
            you have the spec sheet of your probe you can try and setup a custom probe and provide 
            the values. Not all probes will work so YMMV.
          example: grilleye_iris
          default: grilleye_iris    
          enum:
            - custom
            - grilleye_iris
            - ikea_fantast
            - maverick_et733
            - weber_igrill
        reference_kohm:
          type: 
            - "number"
            - "null"
          format: float
          example: 100
          default: 100
          description: The reference resistance value from the spec sheet in kOhm - only used with type CUSTOM
        reference_celcius:
          type: 
            - "number"
            - "null"
          format: float
          example: 25
          default: 25
          description: The reference celcius value from the spec sheet - only used with type CUSTOM
        reference_beta:
          type: 
            - "number"
            - "null"
          format: float
          examples: 
            - 4250
            - null
          default: 4250
          description: The reference beta coefficient value from the spec sheet - only used with type CUSTOM
        
    
    Wifinetwork:
      type: object
      properties:
        ssid:
          type: string
          example: MyHomeWifi
          description: Wifi SSID
        signal_strength:
          type: integer
          example: -61
          description: The wifi signal expressed in dbm. The closer to 0 the better.
        auth_method:
          type: string
          description: The authentication method that is used by the wifi network
          example: wpa2_psk   
          enum:
            - open
            - wep
            - wpa_psk
            - wpa2_psk
            - wpa_wpa2_psk
            - wpa2_enterprise
            - wpa3_psk
            - wpa2_wpa3_psk
            - wpapi_psk
            - unknown
    
    Settings:
      type: object
      properties:
        name:
          type: string
          example: Free-Grilly
          description: The chosen grill name
        unique_id:
          type: string
          format: uuid
          example: 12abc3de-4567-89f0-a123-456b789012c3
          description: The unique id in UUIDv4 format
          readOnly: true
        firmware_version:
          type: string
          example: 25.03.01
          description: The current firmware version in CalVer
          readOnly: true
        temperature_unit:
          type: string
          description: The temperature_unit that is used
          example: celcius
          default: celcius    
          enum:
            - celcius
            - fahrenheit
        beep_enabled:
          type: boolean
          example: true
          description: Is the buzzer enabled
        beep_on_ready:
          type: boolean
          example: true
          description: Beep when the target_temperature is reached
        beep_outside_target:
          type: boolean
          example: true
          description: Beep when a probe is outside of a temperature range
        beep_volume:
          type: integer
          example: 5
          description: The beeper volume from 1-5
        beep_degrees_before:
          type: integer
          example: 5
          description: Beep when the probe reaches this amount of degrees before the target temperature
        screen_timeout_minutes:
          type: integer
          example: 0
          description: How many minutes before the screen turns off automatically. 0 disables the timeout.
        backlight_timeout_minutes:
          type: integer
          example: 0
          description: How many minutes before the backlight turns off automatically. 0 disables the timeout.
        backlight_brightness:
          type: integer
          description: Screen backlight brightness setting (0-5)
          example: 5
          default: 5
          minimum: 0
          maximum: 5
        mqtt_broker:
          type: string
          example: "broker.test.com"
        mqtt_port:
          type: integer
          example: 1883
        mqtt_topic:
          type: string
          example: "free-grilly"
        mqtt_user:
          type: string
          example: ""
        mqtt_password:
          type: string
          example: ""
        wifi_ssid:
          type: string
          example: my-home-wifi
          description: The name of the wifi network that the grill is connected to
        wifi_password:
          type: string
          example: "********"
          description: The wifi password.
        wifi_ip:
          type: string
          example: 192.168.0.10
          description: The wifi ip when connected to your network
        wifi_subnet:
          type: string
          example: 255.255.255.0
          description: The wifi subnet
        wifi_gateway:
          type: string
          example: 192.168.0.1
          description: The wifi gateway
        wifi_dns:
          type: string
          example: 9.9.9.9
          description: The wifi dns
        local_ap_ssid:
          type: string
          example: FreeGrilly
          description: The name of the grill's local wifi network
        local_ap_password:
          type: string
          example: "********"
          description: The local wifi password
        local_ap_ip:
          type: string
          example: 192.168.200.10
          description: The local wifi ip
        local_ap_subnet:
          type: string
          example: 255.255.255.0
          description: The local wifi subnet
        local_ap_gateway:
          type: string
          example: 192.168.200.1
          description: The local wifi gateway

paths:
  /grill:
    get:
      tags:
        - grill
      summary: Current grill info and probes
      description: >
        Get the current needed basic grill information + all the probes and 
        their temperatures
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Grill'
  
  /probes:
    get:
      tags:
        - probes
      summary: Probes
      description: >
        View current probe settings
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                minItems: 8
                maxItems: 8
                items:
                  $ref: '#/components/schemas/Probe'
    post:
      tags:
        - probes
      summary: Probes
      description: >
        Edit probes, you are not required to send all probes. Just send a list of probes that you have modified.
      requestBody:
        required: true
        description: Settings to set
        content:
            application/json:
              schema:
                type: array
                minItems: 1
                maxItems: 8
                items:
                  $ref: '#/components/schemas/Probe'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                minItems: 8
                maxItems: 8
                items:
                  $ref: '#/components/schemas/Probe'
        '400':
          $ref: '#/components/responses/400'
  
  /settings:
    get:
      tags:
        - settings
      summary: Grill settings
      description: >
        Endpoint to view current settings
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Settings'
    post:
      tags:
        - settings
      summary: Grill settings
      description: >
        Endpoint to edit settings
      requestBody:
        required: true
        description: Settings to set
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Settings'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Settings'
        '400':
          $ref: '#/components/responses/400'
    
  /wifiscan:
    get:
      tags:
        - utility
      summary: Scan for wifi networks
      description: >
        Scans for nearby wifi networks, has a long latency of about 5-7 seconds
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                minItems: 0
                items:
                  $ref: '#/components/schemas/Wifinetwork'
